### ISSUE TITLE
 ValueError: could not broadcast input array from shape (172,) into shape (344,) for certain mesh

### ISSUE THREAD

**Issue by tianyyiii** [Samir55/SATR#2]
Thanks for your great work!
When I run segmentation on my customized meshes, for some mesh, it works without error. However, for some other meshes, I get the error 

Traceback (most recent call last):
  File "/home/jianfu/MeshCraft/SATR/scripts/single_dataset_example.py", line 18, in <module>
    segment(
  File "/home/jianfu/MeshCraft/SATR/scripts/helper_functions.py", line 142, in segment
    segmenter.set_mesh(mesh)
  File "/home/jianfu/MeshCraft/SATR/meshseg/methods/segmentors.py", line 187, in set_mesh
    self.compute_vertices_pairwise_dist()
  File "/home/jianfu/MeshCraft/SATR/meshseg/methods/segmentors.py", line 276, in compute_vertices_pairwise_dist
    self.vertices_distances[:, i] = x
ValueError: could not broadcast input array from shape (172,) into shape (344,)
How do I solve this?

**Comment by Samir55** [comment]
Hi @tianyyiii, thank you for reaching out! it seems that the mesh may have duplicate vertices. You may need to preprocess it using Meshlab or similar software.

**Comment by tianyyiii** [comment]
Thank you. It works!

**Comment by sizhe-wang** [comment]
I met the same problem. There may be another probability. So I record here and hope to be helpful. 
I found [this](https://github.com/NVIDIAGameWorks/kaolin/issues/734). This may be a bug of kaolin that if you import an obj mesh with color, the vertices in kaolin will contain RGB values. So that the mesh vertices may double.

I solved this by delete the color information of the obj mesh.
